new GRIC terms added in the new file oeso-gric.owl and removed from oeso.owl
OpenSILEX/ontology-vocabularies pull request #11
Opened 2019-04-18 09:21 UTC by pierreetiennealary

2019-04-18 15:23 UTC, annetireau requested changes

2019-04-18 15:23 UTC, annetireau commented on oeso-gric.owl
> +        <dc:source>skos:closeMatch Level measurement rain gauge (LRG) [IOM-99_FI-RI 2.2.1e] http://www.wmo.int/pages/prog/www/IMOP/publications/IOM-99_FI-RI.pdf</dc:sour
```suggestion
    <owl:Class rdf:about="http://www.opensilex.org/vocabulary/oeso#Grain">
```

2019-04-18 15:23 UTC, annetireau commented on oeso-gric.owl
> +        <dc:source>skos:closeMatch Level measurement rain gauge (LRG) [IOM-99_FI-RI 2.2.1e] http://www.wmo.int/pages/prog/www/IMOP/publications/IOM-99_FI-RI.pdf</dc:sour
What is the difference between grain and kernel ?

2019-04-18 15:23 UTC, annetireau commented on oeso-gric.owl
> +        <dc:source>skos:closeMatch Level measurement rain gauge (LRG) [IOM-99_FI-RI 2.2.1e] http://www.wmo.int/pages/prog/www/IMOP/publications/IOM-99_FI-RI.pdf</dc:sour
```suggestion
    <owl:Class rdf:about="http://www.opensilex.org/vocabulary/oeso#Spikelet">
```

2019-04-18 15:23 UTC, annetireau commented on oeso-gric.owl
> +        <dc:source>skos:closeMatch Level measurement rain gauge (LRG) [IOM-99_FI-RI 2.2.1e] http://www.wmo.int/pages/prog/www/IMOP/publications/IOM-99_FI-RI.pdf</dc:sour
```suggestion
    <owl:Class rdf:about="http://www.opensilex.org/vocabulary/oeso#Stem">
```

2019-04-18 15:23 UTC, annetireau commented on oeso-gric.owl
> +        <dc:source>skos:closeMatch Level measurement rain gauge (LRG) [IOM-99_FI-RI 2.2.1e] http://www.wmo.int/pages/prog/www/IMOP/publications/IOM-99_FI-RI.pdf</dc:sour
```suggestion
    <owl:Class rdf:about="http://www.opensilex.org/vocabulary/oeso#Tassel">
```

2019-04-18 15:23 UTC, annetireau commented on oeso-gric.owl
> +        <dc:source>skos:closeMatch Level measurement rain gauge (LRG) [IOM-99_FI-RI 2.2.1e] http://www.wmo.int/pages/prog/www/IMOP/publications/IOM-99_FI-RI.pdf</dc:sour
```suggestion
    <owl:Class rdf:about="http://www.opensilex.org/vocabulary/oeso#Tiller">
```

2019-04-23 14:50 UTC, annetireau requested changes

2019-04-23 14:50 UTC, annetireau commented on oeso-gric.owl
> +        <dc:source>skos:closeMatch Level measurement rain gauge (LRG) [IOM-99_FI-RI 2.2.1e] http://www.wmo.int/pages/prog/www/IMOP/publications/IOM-99_FI-RI.pdf</dc:sour
Are there 2 labels in english for grain ? grain and kernel ?

2019-04-23 15:36 UTC, pierreetiennealary commented on oeso-gric.owl
> +        <dc:source>skos:closeMatch Level measurement rain gauge (LRG) [IOM-99_FI-RI 2.2.1e] http://www.wmo.int/pages/prog/www/IMOP/publications/IOM-99_FI-RI.pdf</dc:sour
yes, for wheat either grain or kernel can be used

2019-04-23 16:05 UTC, pierreetiennealary commented on oeso-gric.owl
> +        <dc:source>skos:closeMatch Level measurement rain gauge (LRG) [IOM-99_FI-RI 2.2.1e] http://www.wmo.int/pages/prog/www/IMOP/publications/IOM-99_FI-RI.pdf</dc:sour
we distinguish the common term "seed" (PO:0025496) and the more specific term "grain" (PO:0030104) used for Poacea and synonym to caryopsis fruit (and kernel)

2019-04-23 20:29 UTC, annetireau commented on oeso-gric.owl
> +        <dc:source>skos:closeMatch Level measurement rain gauge (LRG) [IOM-99_FI-RI 2.2.1e] http://www.wmo.int/pages/prog/www/IMOP/publications/IOM-99_FI-RI.pdf</dc:sour
Maybe you should create 2 concepts or keep the less specific

2019-05-14 13:30 UTC, pierreetiennealary commented on oeso-gric.owl
> +        <dc:source>skos:closeMatch Level measurement rain gauge (LRG) [IOM-99_FI-RI 2.2.1e] http://www.wmo.int/pages/prog/www/IMOP/publications/IOM-99_FI-RI.pdf</dc:sour
I'll remove the "kernel" and "caryopisi fruit" as pseudo synonyms and replace the "grain" label by "caryopsis fruit" in order to keep the PO term

2019-05-15 11:13 UTC, annetireau requested changes
Please don't commit conflics on oeso-phenoarch.owl

2019-05-15 11:13 UTC, closed without merging